apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user
  namespace: sock-shop
spec:
  hosts:
  - user
  http:
  - fault:
      abort:
        httpStatus: 500
        percent: 100
    match: 
      - uri: 
          prefix: /cards
    route:
    - destination:
        host: user
        subset: v1
  - route:
    - destination:
        host: user
        subset: v1

