apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: payment
  namespace: sock-shop
spec:
  hosts:
  - payment
  http:
  - fault:
      delay:
        fixedDelay: 0.001s
        percentage:
          value: 100
    route:
    - destination:
        host: payment
        subset: v1
  - route:
    - destination:
        host: payment
        subset: v1

