apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user
  namespace: sock-shop
spec:
  hosts:
  - user
  http:
  - fault:
      delay:
        fixedDelay: 30s
        percent: 100
    route:
    - destination:
        host: user
        subset: v1

