apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front-end
  namespace: sock-shop
spec:
  hosts:
  - "*"
  gateways:
  - sockshop-gateway
  http:
  - fault:
      abort:
        httpStatus: 403
        percent: 70
    match:
    - uri:
        prefix: /customers
    route:
    - destination:
        host: user
        subset: v1
  - match:
    - uri: 
        prefix: /login
    - uri: 
        prefix: /register
    - uri: 
        prefix: /cards
    - uri: 
        prefix: /addresses
    route:
    - destination:
        host: user
        subset: v1
  - name: front-end
    route:
    - destination:
        host: front-end
        subset: v1