apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sockshop-gateway
  namespace: sock-shop
spec:
  selector:
    istio: ingressgateway # use istio default controller
  nodeSelector:
    benchmark: "false"
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front-end
  namespace: sock-shop
spec:
  hosts:
  - "*"
  gateways:
  - sockshop-gateway
  http:
  - name: carts
    match:
    - uri:
        prefix: /carts
    route:
    - destination:
        host: carts
  - name: orders
    match:
    - uri:
        prefix: /orders
    route:
    - destination:
        host: orders
  - name: user
    match:
    - uri:
        prefix: /customers
    - uri:
        prefix: /addresses
    - uri:
        prefix: /cards
    route:
    - destination:
        host: user
  - name: front-end
    route:
    - destination:
        host: front-end
        port:
          number: 80
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all
  namespace: sock-shop
spec:
  action: ALLOW
  rules:
  - {}